### ISSUE TITLE
Faction modification page?

### ISSUE THREAD

**Issue by firemaster1294** [uwhvz/uwhvz#11]
Currently the necro needs to go into backend to do this. This sucks. Let's change this?

**Comment by pkrshnan** [comment]
What are the requirements for this ticket? From what I can tell, we need the following:
- [x] Add/Remove Factions (should only be scoped to the current game)
  - [ ] Add/Remove modifiers for each of the factions
- [x] Modify a player's faction (maybe should be done from the manage player's page)
- [x] Have a list of all players belonging to this faction
- [x] Maybe list faction bonuses if possible?
  - This is situational, in that discounts are impossible to show in the UI.
  - Maybe as part of this add discounts as a possible modifier now that we have purchases in the UI?
