### ISSUE TITLE
Fix Broken Tagging

### ISSUE THREAD

**Issue by pkrshnan** [uwhvz/uwhvz#50]
The current tagging system is broken since it used to be reliant on deleting a human and recreating them as a zombie. 

The fix is quite simple, its just adding a new field on `Tags` to be a `Type`. This essentially will be one of two values: `Tag` or `Stun`. `Tag` for zombos, `Stun` for humans. 

We would have to backfill the data from the past terms to match this.

**Comment by uwhvz** [comment]
Closed

**Comment by uwhvz** [comment]
Closed via #51 #52
