### ISSUE TITLE
Improve First Time Guide and Rules

### ISSUE THREAD

**Issue by firemaster1294** [uwhvz/uwhvz#8]
These either need to be done as HTML or reworked to allow the superuser account to easily upload changed files. Here's an idea: have an HTML page that has an option to view PDF that autogenerates on the fly? If we keep everything as PDFs, we need to change the URL linking in the different landing pages so that they all sync. This is how we ran in to issues with multiple versions of rules being on the site before.

- [ ] Improve Rules
- [ ] Improve First Time Guide

**Comment by pkrshnan** [comment]
#19 covers this ticket, so closing.
