### ISSUE TITLE
Allow mods or necro to change signup location data

### ISSUE THREAD

**Issue by firemaster1294** [uwhvz/uwhvz#9]
Currently this can only be done if the necro goes into the backend of django. Do we want mods to have this power to? We should at the very least make this easier to change

**Comment by pkrshnan** [comment]
Looks like most of this is already completed, save for deleting signup locations. I'll add that and this ticket should be done.

**Comment by firemaster1294** [comment]
Sorry to say it, but I totally forgot to mention that the signup location changes should probably cover the signup times function the appears on the index of the main portion of the site. Just need a form capable of doing this. Maybe have 2 drop down tabs, one for the location, one for the day, and then have the text field auto-populate and be editable by this? Alternatively, just have forms similar to the email templates?

**Comment by pkrshnan** [comment]
I'm likely not going to add editing functionality, rather just the functionality to add and delete. I'll improve the current form to have additional fields for accepting strings for each of the day's available times.  Closing this issue, will open another.
